# Generated by Django 4.2.4 on 2023-10-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_linkedin_posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_code",
            field=models.PositiveSmallIntegerField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Image response code",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_code",
            field=models.PositiveSmallIntegerField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Share response code",
            ),
        ),
    ]
