# Generated by Django 4.2.6 on 2023-11-28 10:05

from django.db import migrations, models
import django.db.models.deletion
import django_linkedin_posts.models


class Migration(migrations.Migration):
    dependencies = [
        ("django_linkedin_posts", "0003_post_post_response_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(default="", max_length=140)),
                ("question_text", models.CharField(max_length=140)),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("ONE_DAY", "Poll is open for 1 day"),
                            ("THREE_DAYS", "Poll is open for 3 days"),
                            ("SEVEN_DAYS", "Poll is open for 7 days"),
                            ("FOURTEEN_DAYS", "Poll is open for 14 days"),
                        ],
                        default="THREE_DAYS",
                        max_length=32,
                    ),
                ),
            ],
            bases=(models.Model, django_linkedin_posts.models.BaseLinkedinObject),
        ),
        migrations.CreateModel(
            name="PollOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=30)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_linkedin_posts.poll",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(blank=True, default="Comment text", null=True),
                ),
                (
                    "file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=django_linkedin_posts.models.comment_image_path,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="Image title", max_length=64, null=True
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=django_linkedin_posts.models.image_path,
                    ),
                ),
            ],
            bases=(models.Model, django_linkedin_posts.models.BaseLinkedinObject),
        ),
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.RemoveField(
            model_name="post",
            name="image_code",
        ),
        migrations.RemoveField(
            model_name="post",
            name="image_title",
        ),
        migrations.RemoveField(
            model_name="post",
            name="image_urn",
        ),
        migrations.RemoveField(
            model_name="post",
            name="post_code",
        ),
        migrations.RemoveField(
            model_name="post",
            name="post_response_text",
        ),
        migrations.RemoveField(
            model_name="post",
            name="post_urn",
        ),
        migrations.DeleteModel(
            name="PostShare",
        ),
        migrations.AddField(
            model_name="postimage",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="django_linkedin_posts.post",
            ),
        ),
        migrations.AddField(
            model_name="postcomment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="django_linkedin_posts.post",
            ),
        ),
    ]
