# Generated by Django 4.2.6 on 2023-11-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_linkedin_posts",
            "0004_poll_polloption_postcomment_postimage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="response_code",
            field=models.PositiveSmallIntegerField(
                blank=True, editable=False, null=True, verbose_name="Response code"
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="response_text",
            field=models.TextField(
                blank=True, editable=False, null=True, verbose_name="Response text"
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="urn",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="response_code",
            field=models.PositiveSmallIntegerField(
                blank=True, editable=False, null=True, verbose_name="Response code"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="response_text",
            field=models.TextField(
                blank=True, editable=False, null=True, verbose_name="Response text"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="urn",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="postimage",
            name="response_code",
            field=models.PositiveSmallIntegerField(
                blank=True, editable=False, null=True, verbose_name="Response code"
            ),
        ),
        migrations.AddField(
            model_name="postimage",
            name="response_text",
            field=models.TextField(
                blank=True, editable=False, null=True, verbose_name="Response text"
            ),
        ),
        migrations.AddField(
            model_name="postimage",
            name="urn",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
    ]
