# Generated by Django 4.2.6 on 2023-11-28 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_linkedin_posts",
            "0005_poll_response_code_poll_response_text_poll_urn_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="postcomment",
            old_name="file",
            new_name="image",
        ),
    ]
