# Generated by Django 4.2.6 on 2023-11-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_linkedin_posts", "0006_rename_file_postcomment_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcomment",
            name="response_code",
            field=models.PositiveSmallIntegerField(
                blank=True, editable=False, null=True, verbose_name="Response code"
            ),
        ),
        migrations.AddField(
            model_name="postcomment",
            name="response_text",
            field=models.TextField(
                blank=True, editable=False, null=True, verbose_name="Response text"
            ),
        ),
        migrations.AddField(
            model_name="postcomment",
            name="urn",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
    ]
