# Generated by Django 4.2.6 on 2023-11-28 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_linkedin_posts",
            "0007_postcomment_response_code_postcomment_response_text_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="response_code",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="response_text",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="urn",
        ),
        migrations.RemoveField(
            model_name="post",
            name="response_code",
        ),
        migrations.RemoveField(
            model_name="post",
            name="response_text",
        ),
        migrations.RemoveField(
            model_name="post",
            name="urn",
        ),
        migrations.RemoveField(
            model_name="postcomment",
            name="response_code",
        ),
        migrations.RemoveField(
            model_name="postcomment",
            name="response_text",
        ),
        migrations.RemoveField(
            model_name="postcomment",
            name="urn",
        ),
        migrations.RemoveField(
            model_name="postimage",
            name="response_code",
        ),
        migrations.RemoveField(
            model_name="postimage",
            name="response_text",
        ),
        migrations.RemoveField(
            model_name="postimage",
            name="urn",
        ),
    ]
