# Generated by Django 4.2.7 on 2023-11-28 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_linkedin_posts", "0010_alter_postcomment_imageobj"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PostImage",
            new_name="Image",
        ),
        migrations.RenameField(
            model_name="postcomment",
            old_name="imageobj",
            new_name="image",
        ),
    ]
