# Generated by Django 4.2.7 on 2023-11-28 21:09

from django.db import migrations, models
import django.db.models.deletion
import django_linkedin_posts.models


class Migration(migrations.Migration):
    dependencies = [
        ("django_linkedin_posts", "0011_rename_postimage_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(blank=True, default="Comment text", null=True),
                ),
            ],
            bases=(models.Model, django_linkedin_posts.models.BaseLinkedinObject),
        ),
        migrations.CreateModel(
            name="CommentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_linkedin_posts.comment",
                    ),
                ),
            ],
            bases=(models.Model, django_linkedin_posts.models.BaseLinkedinObject),
        ),
        migrations.RenameField(
            model_name="post",
            old_name="comment",
            new_name="text",
        ),
        migrations.RenameModel(
            old_name="Image",
            new_name="PostImage",
        ),
        migrations.DeleteModel(
            name="PostComment",
        ),
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_linkedin_posts.postimage",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="django_linkedin_posts.post",
            ),
        ),
    ]
