# Generated by Django 4.2.7 on 2023-11-30 20:34

from django.db import migrations, models
import django_linkedin_posts.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_linkedin_posts",
            "0012_comment_created_at_comment_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="poll",
            old_name="comment",
            new_name="comment_text",
        ),
        migrations.RenameField(
            model_name="postimage",
            old_name="title",
            new_name="image_title",
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="commentimage",
            name="image",
            field=models.ImageField(
                null=True, upload_to=django_linkedin_posts.models.comment_image_path
            ),
        ),
    ]
