# Generated by Django 4.2.7 on 2023-11-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_linkedin_posts", "0013_rename_comment_poll_comment_text_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postimage",
            old_name="image_title",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="poll",
            name="comment_text",
            field=models.TextField(default="", max_length=140),
        ),
        migrations.AlterField(
            model_name="poll",
            name="question_text",
            field=models.TextField(max_length=140),
        ),
    ]
