# Generated by Django 4.2.7 on 2023-11-30 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_linkedin_posts", "0014_rename_image_title_postimage_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="poll",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_linkedin_posts.poll",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_linkedin_posts.post",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(null=True),
        ),
    ]
